version: "2"
services:
  neo4j:
    image: "neo4j:4.2"
    volumes:
      - "./data/:/data"
      - "./log/:/log"
      - "./conf/:/conf"
      - "./import//var/lib/neo4j/import"
      - "./plugins/:/plugins"
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    env_file:
      - neo4j.env
  api:
    command: /bin/bash -c "uvicorn app.main:app --reload --host 0.0.0.0 --port 80"
    build:
      context: ./api/docker/
      dockerfile: Dockerfile
    volumes:
      - ./api/:/app
    working_dir: /
    ports:
      - "80:80"
  notebook:
    command: /bin/bash -c "jupyter lab --ip=0.0.0.0 --allow-root"
    image: pure_notebook:3.7
    volumes:
      - "./notebooks/:/home/work/"
    ports:
      - "8888:8888"
    env_file:
      - neo4j.env
